microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: "pagopa-ecommerce-reporting-functions"
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommercereportingfunctions
    tag: "1.2.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.prod.platform.pagopa.it"
    path: /ppagopa-ecommerce-reporting-functions/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  envConfig:
    ASPNETCORE_URLS: "http://*:8080"
    FUNCTIONS_SECRETS_PATH: "/tmp/secrets"
    WEBSITE_SITE_NAME: "pagopaecommercereportingfunctions"
    FUNCTIONS_WORKER_RUNTIME: "java"
    ECOMMERCE_CLIENTS_LIST: "[\"IO\",\"CHECKOUT\",\"CHECKOUT_CART\",\"WISP_REDIRECT\"]"
    ECOMMERCE_PAYMENT_METHODS_TYPE_CODE_LIST: "[\"CP\",\"PPAL\",\"BPAY\",\"RPIC\",\"RBPS\",\"RBPP\",\"RBPR\",\"MYBK\",\"SATY\",\"APPL\",\"RICO\",\"GOOG\"]"
    ECOMMERCE_PAYMENT_METHODS_PSP_LIST: "{\"CP\":[\"BCITITMM\",\"CIPBITMM\",\"BIC36019\",\"UNCRITMM\",\"BPPIITRRXXX\",\"PPAYITR1XXX\",\"BNLIITRR\",\"PASCITMM\",\"WOLLNLB1\",\"BPMOIT22\",\"SARDIT31\",\"IFSPIT21\",\"BCEPITMM\"],\"PPAL\":[\"BCITIMM\",\"SIGPITM1XXX\"],\"MYBK\":[\"BCITIMM\",\"UNCRITMM\"],\"BPAY\":[\"BCITIMM\"],\"SATY\":[\"SATYLUL1\"],\"APPL\":[\"SIGPITM1XXX\"],\"GOOG\":[\"CIPBITMM\"],\"RPIC\":[\"RPIC\"],\"RBPS\":[\"RBPS\"],\"RBPP\":[\"RBPP\"],\"RBPR\":[\"RBPR\"],\"RICO\":[\"RICO\"]}"
    HELPDESK_SERVICE_URI: "https://api.platform.pagopa.it/ecommerce/helpdesk-service/v2"
    HELPDESK_SERVICE_API_ENDPOINT: "/ecommerce/searchMetrics"
    ECOMMERCE_REPORTING_TABLE: "TransactionStatusReporting"
    NCRON_SCHEDULE_CHECKOUT: "0 1 * * * *"
    NCRON_SCHEDULE_IO: "0 11 * * * *"
    NCRON_SCHEDULE_CHECKOUT_CART: "0 21 * * * *"
    NCRON_SCHEDULE_WISP_REDIRECT: "0 31 * * * *"
    NCRON_SCHEDULE_SLACK_REPORTING: "0 20 9 * * Mon"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    ECOMMERCE_SLACK_REPORTING_WEBHOOK_ENDPOINT: ecommerce-reporting-webhook-url-slack
    AzureWebJobsStorage: ecommerce-storage-reporting-connection-string
    HELPDESK_SERVICE_API_KEY: helpdesk-service-api-key-for-reporting
    ECOMMERCE_REPORTING_CONNECTION_STRING: ecommerce-storage-reporting-connection-string
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  azure:
    workloadIdentityClientId: "d5614882-90dd-47a1-aad1-cdf295201469"
